services:
  rp_centric_sca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rp_centric_sca
    ports:
      - "8087:8087"
    environment:
      OAUTH2_CLIENT_ID:
      OAUTH2_CLIENT_SECRET:
      OAUTH2_AUTHORIZATION_GRANT_TYPE: